export function Features() {
  const features = [
    {
      title: 'AI-Powered Roadmaps',
      description: 'Get personalized learning paths generated by AI based on your skill level and preferences.',
      icon: (
        <svg className="w-12 h-12 text-primary-orange" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      ),
    },
    {
      title: 'Free Resources Only',
      description: 'Access curated collections of 100% free learning materials from trusted sources.',
      icon: (
        <svg className="w-12 h-12 text-primary-orange" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h2v6h-2zm0 8h2v2h-2z" fill="currentColor"/>
        </svg>
      ),
    },
    {
      title: 'Progress Tracking',
      description: 'Track your learning journey with detailed progress monitoring and achievements.',
      icon: (
        <svg className="w-12 h-12 text-primary-orange" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          <path d="M12 8v4l3 3" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      ),
    },
    {
      title: 'Custom Roadmaps',
      description: 'Create and share your own learning paths with the community.',
      icon: (
        <svg className="w-12 h-12 text-primary-orange" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M4 6h16M4 12h16M4 18h7" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      ),
    },
    {
      title: 'Expert Verified',
      description: 'All roadmaps are verified by experts to ensure quality and relevance.',
      icon: (
        <svg className="w-12 h-12 text-primary-orange" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      ),
    },
    {
      title: 'Learning Styles',
      description: 'Choose resources that match your preferred learning style - video, text, or interactive.',
      icon: (
        <svg className="w-12 h-12 text-primary-orange" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      ),
    },
  ]

  return (
    <section id="features" className="py-20 bg-primary-white">
      <div className="container">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Supercharge Your{' '}
            <span className="text-primary-orange">Learning</span>
          </h2>
          <p className="text-lg text-primary-black/70 max-w-2xl mx-auto">
            Discover powerful features that make learning any subject easier, faster, and more effective.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="brutal-card hover:scale-[1.02] hover:rotate-1 transition-transform p-6"
            >
              <div className="mb-4">{feature.icon}</div>
              <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
              <p className="text-primary-black/70">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
} 